# -*- mode:python -*-

# Copyright (c) 2016 The Pennsylvania State University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANsTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Contact: Shulin Zhao (suz53@cse.psu.edu)

Import('*')
#SConscript(['allocators/SConscript',
 #           'routers/SConscript',
  #          'arbiters/SConscript',
#	    'networks/SConscript'])
Source('interconnect.cpp')
Source('trafficmanager.cpp')
Source('booksim_config.cpp')
Source('buffer.cpp')
Source('buffer_monitor.cpp')
Source('buffer_state.cpp')
Source('config_utils.cpp')
#Source('booksim.hpp')
#Source('channel.hpp')
Source('credit.cpp')
Source('flitchannel.cpp')
Source('flit.cpp')
#Source('globals.hpp')
Source('injection.cpp')
Source('lex.yy.c')
Source('misc_utils.cpp')
Source('module.cpp')
Source('outputset.cpp')
Source('packet_reply_info.cpp')
#Source('pipefifo.hpp')
Source('random_utils.cpp')
#Source('rng.c')
#Source('rng-double.c')
Source('rng_double_wrapper.cpp')
Source('rng_wrapper.cpp')
Source('routefunc.cpp')
Source('stats.cpp')
Source('switch_monitor.cpp')
#Source('timed_module.hpp')
Source('traffic.cpp')
Source('vc.cpp')
Source('y.tab.c')
Source('batchtrafficmanager.cpp')
